In [23]:
import pandas as pd 
import numpy as np
df= pd.read_csv("diabetes.csv")

In [ ]:
df.isnull().sum()

In [13]:
def FillValue():
   
    if df.empty:
        return df
    
    for column in df.columns:
        if df[column].dtype in [np.int64, np.float64]:
            mean = df[column].mean()
            df[column].fillna(mean, inplace=True)
        else:
            df[column].fillna(df[column].mode()[0], inplace=True)
        
    return df

In [14]:
print("FILL all  MISSING VALUES with their mean median mode  ")
df_filled =  FillValue()
df_filled

FILL all  MISSING VALUES with their mean median mode

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [24]:
for col in df.dtypes[df.dtypes=="object"].index:
    for_dummy = df.pop(col)
    df = pd.concat([df, pd.get_dummies(for_dummy, prefix=col)], axis=1)
    df.head()

In [25]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [16]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [19]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(,y,test_size=0.25)

In [20]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_train,Y_train)

RandomForestClassifier()

In [21]:
y_pred=rf.predict(X_test)

In [22]:
from sklearn.metrics import roc_curve,auc
false_positive_rate, true_positive_rate, thresholds =roc_curve(Y_test ,y_pred)
roc_auc=auc(false_positive_rate ,true_positive_rate)
roc_auc

0.7527777777777778